export const data = {
  products: [
    {
      id: 1,
      title: 'Galaxy Note 9',
      subtitle: 'Galaxy Note 9',
      inventory: 500,
      description: 'Lit',
      imgSrc: ['http://localhost:0000'],
      options: [],
      price: 100,
      currency: '$',
    },
    {
      id: 2,
      title: 'iPhone XS',
      subtitle: 'iPhone XS',
      inventory: 500,
      description: 'Lit',
      imgSrc: ['http://localhost:0000'],
      options: [],
      price: 100,
      currency: '$',
    },
    {
      id: 3,
      title: 'Google Pixel 3',
      subtitle: 'Google Pixel 3',
      inventory: 500,
      description: 'Lit',
      imgSrc: ['http://localhost:0000'],
      options: [],
      price: 100,
      currency: '$',
    },
  ],
  cart: [],
}
